### ISSUE TITLE
Handle 'UnhandledPromiseRejection' warning during 'npm run start(dev)'

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#102]
After booting the redis using 'docker start redis' , many UnhandledPromiseRejection warnings are logged.
Proposal: Fix them.

**Comment by kichloo** [comment]
@Parikshit-Hooda I can work on this issue. But, pl give the file which is to be modified.

**Comment by Parikshit-Hooda** [comment]
@kichloo figure it out yourself. you'll learn. you should get a hint of code to fix when you run the said script(npm run ....)

**Comment by akshaysingh5** [comment]
I would like to issue. Please assign me.

**Comment by luisgdelahozl** [comment]
Hi, I would like to work on it

**Comment by coderwassananmol** [comment]
Feel free to submit PR.

**Comment by coderwassananmol** [comment]
Not required anymore.
