### ISSUE TITLE
implement issue templates

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#103]
use https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository and implement issue templates.
end result: https://github.com/CircuitVerse/CircuitVerse/issues/new/choose a menu like this.

**Comment by ishukhanchi** [comment]
Please assign this one to me.
Interested.

**Comment by Parikshit-Hooda** [comment]
@ishukhanchi please update.

**Comment by ishukhanchi** [comment]
Sir, sorry for the delay. I'm on this.

**Comment by Parikshit-Hooda** [comment]
please link this issue in the pr.
