### ISSUE TITLE
Configure husky to lint staged changes.

### ISSUE THREAD

**Issue by rkpattnaik780** [coderwassananmol/BUB2#106]
Currently there are no pre-commit hooks to pretify the code. It will be good if the project can have a `husky` and `prettier` configured such that the staged files will get prettified before being commited.

**Comment by jamesjose03** [comment]
@rkpattnaik780 @Parikshit-Hooda I would like to work on this issue.

**Comment by Parikshit-Hooda** [comment]
@jamesjose03 go ahead. Please update us within 3 days, here, on the progress

**Comment by jamesjose03** [comment]
Okay thanks
