### ISSUE TITLE
add case to implement OBP in components/books.js

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#109]
Update components/books.js to integrate 'open book publishers' library.
Just like case for google books and panjab digital library are implemented, do for open book publishers as well.
Note/Result: The necessary output is the same as the implementation for the case of 'gb' and 'pn'.
Required: Test this feature heavily on local machines/ error handling. 

More information can be asked on this thread.

**Comment by BhuwanChandra** [comment]
@Parikshit-Hooda I would like to work on this. please assign this to me

**Comment by Parikshit-Hooda** [comment]
@BhuwanChandra go ahead.

**Comment by BhuwanChandra** [comment]
@Parikshit-Hooda can you tell me, where I will get the info of a particular book in OBP APIs.

**Comment by Parikshit-Hooda** [comment]
https://github.com/coderwassananmol/BUB2/blob/develop/HELP_WANTED.md check this for more.
