### ISSUE TITLE
Add TOC to README.md

### ISSUE THREAD

**Issue by jamesjose03** [coderwassananmol/BUB2#110]
## Description
The README is a long one. Adding a Table of Contents will make it easier for navigating through it.
This is what I am proposing to implement.

## Screenshot:
![image](https://user-images.githubusercontent.com/31133182/77815300-a49d1f80-70df-11ea-97e8-e415bd38ce19.png)

**Comment by jamesjose03** [comment]
I am a GSSOC participant. I would like to work on this issue

**Comment by Parikshit-Hooda** [comment]
This issue won't be covered under gssoc.

**Comment by cohky16** [comment]
Please assign this one to me and check pull request.
