### ISSUE TITLE
auto open of browser window when bub2 boots

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#112]
When the project boots up using 'npm run start' or 'npm run dev', it should automatically open a browser tab for the project.
Note: Please enquire if this is actually done already(I haven't experienced this feature). Also, check for the easiest, stable, and requires 'no dependency' way to do this..

**Comment by BhuwanChandra** [comment]
@Parikshit-Hooda I would like to work on this issue. please assign this to me.

**Comment by Parikshit-Hooda** [comment]
@BhuwanChandra go ahead
