### ISSUE TITLE
migrate faq file to new location

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#118]
**Is your feature request related to a problem? Please describe.**
Yes, the current location to the faq.md might change. also, a user might not want to visit the github repo for the faq.

**Describe the solution you'd like**
* An independent HTML or a file which contains the same faq as the faq.md file in this repo. 
* the idea is to decouple the faq from the repo. 
* do make sure to open a new tab when a visitor clicks on the faq file.
*  update the relevant links in the repo so that the migration is implemented.

**Describe alternatives you've considered**
no.

**Additional context**
agreed by the mods meeting to do this.

**Comment by Endowmissy** [comment]
I will like to work on this issue, please assign it to me.

**Comment by Parikshit-Hooda** [comment]
@Endowmissy you may go ahead. Before I assign it to you, please describe what is the intended end result of this issue, in your mind,  so that I know that you understand it correctly. If you don't understand it correctly, i would provide more clarity on this.

**Comment by Endowmissy** [comment]
@Parikshit-Hooda kindly make it more clear to me. Thanks

**Comment by shreyakapoor08** [comment]
@Parikshit-Hooda  can I work on this ?

**Comment by Parikshit-Hooda** [comment]
currently the faq on https://bub2.toolforge.org/ leads to the faq file on the repo. this was a temporary fix. now, it should move to a separate independent page/location.

**Comment by Parikshit-Hooda** [comment]
@shreyakapoor08 you may submit a pr as well.

**Comment by Parikshit-Hooda** [comment]
@shreyakapoor08 @Endowmissy please update on the progress

**Comment by akshaysingh5** [comment]
I would like to work on this issue. Probably I am going to upload the faq file to AWS S3 or some other flat-file storage in the cloud.

**Comment by Parikshit-Hooda** [comment]
@akshaysingh5 I think this is done. https://github.com/coderwassananmol/BUB2/pull/132
