### ISSUE TITLE
Fetch basic details of the book before uploading Google Books

### ISSUE THREAD

**Issue by rkpattnaik780** [coderwassananmol/BUB2#119]
Currently the home page doesn't validate if the entered book ID is valid. It would be great if a GET request could be made onChange of the BookID input value to check if the ID exists and also to fetch some basic details regarding the book including Name, Cover, etc.

For extracting details, we can use scraping libraries like [Cheerio](https://www.npmjs.com/package/cheerio).

We can use the fetched details for preview purposes.

**Comment by IuliaElizaS** [comment]
Hi, I would like to give it a try. Please assign it to me.

**Comment by ankitjena** [comment]
Go ahead. If you face any difficulties, feel free to reach out in slack.

**Comment by IuliaElizaS** [comment]
Ok, thank you!

**Comment by IuliaElizaS** [comment]
Hi, I can't work on this issue anymore due to personal problems. Please unasign me so others can fix it before the GSSOC program ends.
Thank you.

**Comment by coderwassananmol** [comment]
This has been already implemented. Not required anymore.
