### ISSUE TITLE
Show a preview of book before initiating an upload

### ISSUE THREAD

**Issue by rkpattnaik780** [coderwassananmol/BUB2#120]
Currently there is no provision to get a preview of the book we want to upload. To check which book is being addresses, the user has to manually enter the URL with the book ID.

It would be good for the UX if the user could see a preview of the book.

Should be fixed after #119 #121

**Comment by ankitjena** [comment]
We can have /preview route which will take the following metadata
- title
- author
- description
- cover 
and show a preview.

**Comment by BhuwanChandra** [comment]
@rkpattnaik780 @ankitjena I would like to work on this issue. please assign me.

**Comment by ankitjena** [comment]
@BhuwanChandra The issue is blocked until #119 and #121 . You can take them up first

**Comment by BhuwanChandra** [comment]
@ankitjena can I work on this now?

**Comment by rkpattnaik780** [comment]
The issue is still blocked. It can be assigned only after #119 and #121 are fixed.

**Comment by IuliaElizaS** [comment]
please assign me this issue, since is connected to the issue I'm working on. Thank you.

**Comment by IuliaElizaS** [comment]
Hi, I can't work on this issue anymore due to personal problems. Please unasign me so others can fix it before the GSSOC program ends.
Thank you.

**Comment by coderwassananmol** [comment]
Not needed.
