### ISSUE TITLE
Get details of book from Panjab Digital Library for preview purposes

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#121]
## Background
Currently the user cannot preview a book before uploading. We want to fetch details of the book so that they can be used to show the preview component. This is to be done for Panjab Digital Library.

## TODO
Use a scraping library to make a request to book url and get details which should include
- title
- author
- description
- cover

You can use a library like `cheerio` to do the scraping.

**Comment by BhuwanChandra** [comment]
@ankitjena I would like to work on this issue. please assign me.

**Comment by ankitjena** [comment]
@BhuwanChandra Sure go ahead

**Comment by BhuwanChandra** [comment]
@ankitjena @rkpattnaik780 in which file should I add the code?

**Comment by ankitjena** [comment]
@BhuwanChandra Add a file inside `utils` folder called `scraper` or `metadata`. That will hold scraper for all 3 libraries.
