### ISSUE TITLE
Get Details of book from OBP for book preview

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#124]
This issue is similar to #119 and #121 . We need to get the `title`, `author`, `description` and `cover image` to be used for previewing the book. We can use web scraping packages like `cheerio` to do this

**Comment by rinsacm** [comment]
@ankitjena  I would like to work on this issue. Please assign to me.

**Comment by ankitjena** [comment]
@rinsacm I would suggest looking at #123 first. That will help for this and needs to be done first. Feel free to ask if you have any queries regarding that.

**Comment by akshaysingh5** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by coderwassananmol** [comment]
OBP has been removed from the list.
