### ISSUE TITLE
Upload book downloaded from OBP to Internet Archive

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#125]
Upload the book which we get from Open Book Publishers library to Internet archive.
- [ ] Check how we upload books in case of Google Books and PDL
- [ ] Implemented a similar logic for this case.

To be done after #123

**Comment by Rukmini-Meda** [comment]
@ankitjena I would like to work on #123 and this issue as well. Please assign this to me as part of GSSoC'20.

**Comment by ankitjena** [comment]
Sure go ahead @Rukmini-Meda

**Comment by coderwassananmol** [comment]
OBP is not required for now.
