### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sapna2001** [coderwassananmol/BUB2#127]
Readme can be updated with details of mentors,admins,slack channels and details of gssoc. Please assign me this issue.

**Comment by Amitsharma45** [comment]
i want work on this issue please assigm this issue to me

**Comment by ampsteric** [comment]
I can get it done.
please assign

**Comment by coderwassananmol** [comment]
Since this project is exclusively for Wikimedia, we should refrain it from doing it. Thanks guys.
