### ISSUE TITLE
add link to internet archive in readme.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#133]
**Describe the bug**
Add link to the phrase 'Internet Archive'. Link to add : https://archive.org/

> A book uploader bot that transfers documents from public libraries such as Google Books, and Punjab Digital Library etc to **Internet Archive**. Built for Wikimedia Tool Labs. Check out BUB2 on Toolforge!

1. Go to 'https://github.com/coderwassananmol/BUB2/blob/develop/README.md'
2. See the bold phrase.
 > A book uploader bot that transfers documents from public libraries such as Google Books, and Punjab Digital Library, etc to **Internet Archive**. Built for Wikimedia Tool Labs. Check out BUB2 on Toolforge!
3. See error

**Expected behavior**
A link to the Internet Archive to be added.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
Not applicable.

**Comment by arghac14** [comment]
@Parikshit-Hooda assign me this
