### ISSUE TITLE
Files from Panjab Digital Library failed to become PDFs

### ISSUE THREAD

**Issue by satdeepgill** [coderwassananmol/BUB2#138]
**Describe the bug**
Out of a total of 115 works uploaded to IA from Panjab Digital Library using the tool, 100 failed to become PDF. These are only available as ZIP files or torrents. 

Here is the entire list of works uploaded from PDL:

https://archive.org/search.php?query=source%3A%22Punjab+Digital+Library%22&page=3

**Comment by coderwassananmol** [comment]
@satdeepgill Please write an e-mail to collections-service@archive.org. Apparently, the derive tasks fail if JPEG conversion exceeds 2 GB. They have to be restarted by an admin.
