### ISSUE TITLE
Remove email field from the home page

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#140]
Need to remove e-mail field from home page.

**Comment by adripo** [comment]
I will to that

**Comment by Rupesh-2003** [comment]
Hey I would like to work on it

**Comment by ritik307** [comment]
I am interested in working on this issue

**Comment by coderwassananmol** [comment]
@Rupesh-2003 Assigned you! Good luck.

**Comment by coderwassananmol** [comment]
> I am interested in working on this issue

Please take a look at other open issues. :)

**Comment by NitipatTh** [comment]
I would like to work on it :)

**Comment by Rupesh-2003** [comment]
sorry @coderwassananmol, but I can't contribute to the project, You may assign it to someoneElse...

**Comment by NitipatTh** [comment]
I would like to work on it

**Comment by zahrafalah** [comment]
Hey, I am interested in this

**Comment by sPreet247** [comment]
Hey,I would like to work on this

**Comment by coderwassananmol** [comment]
Hi guys, feel free to submit a PR since there are a lot of requests now.

**Comment by kavyashree1903** [comment]
I would like to work on this.

**Comment by coderwassananmol** [comment]
This has been fixed.
