### ISSUE TITLE
Update README.md to include contributing guidelines

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#15]
The contributing guidelines are already in CONTRIBUTING.md file. We need to update the README.md to show the users contributing guidelines.

**Comment by Ijebusoma** [comment]
Hi, any assignee yet for this task? If none, I'll like to take it up

**Comment by coderwassananmol** [comment]
> Hi, any assignee yet for this task? If none, I'll like to take it up

Hi @Ijebusoma, PR has already been made and merged. Please take up any other issue. Thanks.
