### ISSUE TITLE
Increase Modularity in code

### ISSUE THREAD

**Issue by guptavarun619** [coderwassananmol/BUB2#26]
```./component/ParticularBook.js``` and ```./component/Books.js``` are too long to review at once. It can be improved by creating seperate style sheet and seperate modular component (if necessary).

**Comment by Major2001** [comment]
@coderwassananmol  I would like to work on this issue

**Comment by guptavarun619** [comment]
It's better to create separate `style.css` for components in my opinion shall i send a PR regarding this?

**Comment by coderwassananmol** [comment]
Hi guys, I don't want a separate CSS file. We styled jsx that is compiled and lazy-loaded in run time for a specific component. You can increase modularity in other aspects if you feel.

**Comment by meghaa105** [comment]
I would like to take this up........

**Comment by Parikshit-Hooda** [comment]
@meghaa105 Are you interested in working on this issue? Please have a discussion here to understand what is needed to be done to modularise the application. Thanks. If you are interested, please comment here and we'll assign it to you.

**Comment by kichloo** [comment]
@Parikshit-Hooda Being a beginner, can I take this issue? I would also like to discuss about how to go about it.

**Comment by Parikshit-Hooda** [comment]
this issue is up for grabs.

**Comment by meghaa105** [comment]
I am interested

**Comment by Parikshit-Hooda** [comment]
@meghaa105 go ahead.

**Comment by Parikshit-Hooda** [comment]
@meghaa105 is ther any progress on this issue or not? please update by midnight.

**Comment by Dishebh** [comment]
@Parikshit-Hooda can I take up the issue, if it is still up for grabs?

**Comment by coderwassananmol** [comment]
The modularity in code will be fixed in the next release. Closing this issue.
