### ISSUE TITLE
Add docker-compose file for easy redis setup

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#29]
## Background
Docker eases up setting up databases and other services. Having a docker-compose file in repository allows users to just do `docker-compose up` and get everything setup.

## TODO
- Add docker-compose file with the redis service
- Update setup instructions in readme accordingly

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by adityabisoi** [comment]
@ankitjena I can work on this issue

**Comment by ankitjena** [comment]
@vipuldcoder @adityabisoi Feel free to make PR!

**Comment by LMPerera** [comment]
https://github.com/coderwassananmol/BUB2/issues/29
