### ISSUE TITLE
New design for the homepage

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#31]
We need a new UI for the homepage. The current UI is user-friendly but it needs to be tweaked.
Here's what I am expecting:
1. The fields should remain the same, except that e-mail field should now be optional.
2. A solid background color, the fields can have a border.
3. Use some [developer friendly fonts](https://scotch.io/bar-talk/top-10-monospace-fonts-for-developers).

These are simplest requirements. If you have a knack for web designing, feel free to show the creativity.

**Important**
1. Please note that, before you head to design, please submit a wireframe. It can be a photoshop file, marvel app link, or even a design you made on a piece of paper. :)
2. Participants can collaborate together for this issue.

**Comment by Samarjiit** [comment]
Hey, i am interested in working on this issue.

**Comment by coderwassananmol** [comment]
> Hey, i am interested in working on this issue.

Do you want to work alone or you need some help? Feel free to collaborate and submit a sample wireframe.

**Comment by Samarjiit** [comment]
@coderwassananmol  it will be good if someone can collaborate with me for this issue.

**Comment by coderwassananmol** [comment]
> @coderwassananmol it will be good if someone can collaborate with me for this issue.

You can find another participant to work on this with you.

**Comment by guptavarun619** [comment]
I would like to work on this issue with @Samarjiit. Please assign me this issue if i can collaborate on this.

**Comment by meghaa105** [comment]
Can I take this up?

**Comment by ankitjena** [comment]
You guys can use [Figma](https://www.figma.com/) for this.

**Comment by meghaa105** [comment]
So I should be working on this or not?

**Comment by guptavarun619** [comment]
> You guys can use [Figma](https://www.figma.com/) for this.

Please assign the issue and provide a deadline for the same.

**Comment by coderwassananmol** [comment]
@guptavarun619 @meghaa105 @Samarjiit You guys can work together if you want.
There is no such deadline but I will be needing updates from all of you.

**Comment by coderwassananmol** [comment]
@guptavarun619 @meghaa105 @Samarjiit Any updates on this issue?

**Comment by guptavarun619** [comment]
I'll get back to you with a mockup today for further assistance @coderwassananmol .

**Comment by rkpattnaik780** [comment]
Fixed by #68 .
