### ISSUE TITLE
Add GitHub star and fork plugin

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#33]
This should appear on top left on every page.

**Comment by adityabisoi** [comment]
@coderwassananmol I can work on this. Please assign me. Thanks.

**Comment by coderwassananmol** [comment]
> @coderwassananmol I can work on this. Please assign me. Thanks.

Feel free to submit a PR!

**Comment by meghaa105** [comment]
Can I take this up?

**Comment by coderwassananmol** [comment]
> Can I take this up?

It's already taken and PR is being reviewed. Please take any other issue.
