### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#34]
This static footer should say:
"Made with ❤ for [WMF Logo]"
"License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en) Author: [User:Neolux](https://en.wikipedia.org/wiki/User:Neolux)
Use [this](https://commons.wikimedia.org/wiki/File:Wikimedia_Foundation_Logo.png) file for WMF logo
Since the image has CC BY-SA 4.0 license, don't forget to give proper credit.

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. please assign this to me.

**Comment by coderwassananmol** [comment]
> @coderwassananmol I would like to work on this issue. please assign this to me.

Please go ahead!

**Comment by coderwassananmol** [comment]
@BhuwanChandra Any updates on the issue?

**Comment by BhuwanChandra** [comment]
working on it, I will try to make a PR by tomorrow
