### ISSUE TITLE
Make the e-mail field optional

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#35]
Currently, the email field is mandatory, even if the user doesn't want to share his/her email. I don't want the e-mail field to appear at all, if the user doesn't want the update on e-mail.

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. please assign this to me.

**Comment by coderwassananmol** [comment]
> @coderwassananmol I would like to work on this issue. please assign this to me.

Please go ahead!
