### ISSUE TITLE
Modify instructions for local setup in README.md

### ISSUE THREAD

**Issue by rkpattnaik780** [coderwassananmol/BUB2#38]
The [Getting Started](https://github.com/coderwassananmol/BUB2#getting-started) section of `README.md` makes it look like docker is compulsory for local setup of the project. The instructions should be more sectionalized and the docker setup instructions should be within another section.

You might refer [this link](https://github.com/coderwassananmol/BUB2/tree/8d97fed59bdccfb4c6af438057061e2907f373f8#local-setup-instructions) to know how the project can be setup without docker.

**Comment by rkpattnaik780** [comment]
To get a better idea about sectionalization, you can refer to this doc: [Setting_up_Habitica_Locally_on_Linux](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux).

**Comment by adityabisoi** [comment]
@rkpattnaik780 I can improve the documentation. Please assign me the issue.
