### ISSUE TITLE
Add instructions for raising pull request in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rkpattnaik780** [coderwassananmol/BUB2#39]
To make things slightly organized the project should have guidelines regarding writing commit messages and raising a PR. We can have another heading in the `CONTRIBUTING.md` for PRs. For now we have thought of two important instructions : 

1. A PR should have only one commit. Multiple commits should be squashed.
2. Commit messages should follow a certain guideline. For example the [Udacity Git Style Guide](https://udacity.github.io/git-styleguide/).

P.S : Feel free to add more instructions if anything important is getting overlooked.

**Comment by guptavarun619** [comment]
I would like to contribute in this documentation process, If I may. And may contributors are new to using git as version controlling tool. The CONTRIBUTING.md should be beginner friendly too. Please assign me this issue.

**Comment by rkpattnaik780** [comment]
> I would like to contribute in this documentation process, If I may. And may contributors are new to using git as version controlling tool. The CONTRIBUTING.md should be beginner friendly too. Please assign me this issue.

That's exactly how we want the `CONTRIBUTING.md` to be. Feel free to ask anything.

**Comment by meghaa105** [comment]
Can I take this up?

**Comment by rkpattnaik780** [comment]
> Can I take this up?

Hello Megha, this issue has been already assigned. It will be great if you could look at some of our unclaimed issues.
