### ISSUE TITLE
Change the name of /queue route to /stats route

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#40]
Should be done before #41  #42 #43

**Comment by Endowmissy** [comment]
I am interested,can I take this up??

**Comment by coderwassananmol** [comment]
> I am interested,can I take this up??

Feel free to submit a PR!

**Comment by coderwassananmol** [comment]
@Endowmissy Any update?

**Comment by Endowmissy** [comment]
Sorry,I haven't updated you,please check your dm in the slack channel

**Comment by Parikshit-Hooda** [comment]
The PR for this issue is merged. I will close this issue now. @Endowmissy Please second this.

**Comment by Endowmissy** [comment]
oops, just seeing this now.
