### ISSUE TITLE
Show number of books uploaded from BUB2 to internet archive

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#41]
Internet Archive has advanced search API that has an extensive search feature. Search for uploaded by "bub.wikimedia".
Show it in the new /stats route below the queue information. Style accordingly.

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. please assign this to me

**Comment by coderwassananmol** [comment]
> @coderwassananmol I would like to work on this issue. please assign this to me

Please take a look at #40 first. This should be taken after that.

**Comment by coderwassananmol** [comment]
@BhuwanChandra You can start working on it as an individual piece.

**Comment by coderwassananmol** [comment]
@BhuwanChandra Any updates?

**Comment by BhuwanChandra** [comment]
working on this. should I make a PR when #40 will close?

**Comment by coderwassananmol** [comment]
> working on this. should I make a PR when #40 will close?

You can make a PR now. The PR can be updated at any point of time with the new route path.

**Comment by Parikshit-Hooda** [comment]
@BhuwanChandra Please respond.

**Comment by BhuwanChandra** [comment]
I'm working on it, I will make a PR by tomorrow.
