### ISSUE TITLE
Make a /queue/list route

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#44]
1. Show name of the library on top
2. Add 4 buttons - Waiting (<No. of jobs in waiting>) Completed (<No. of jobs in Completed>) Failed (<No. of jobs in failed>) Delayed (<No. of jobs in Delayed>)
3. Within the brackets in the design, show the number of jobs of that specified type. This functionality has already been done in the current /queue page. Check the API for more information.

Sample design (It's very minimal, styling can be taken care of later on):
![:queue:list](https://user-images.githubusercontent.com/12458972/75813302-c099f380-5db5-11ea-80f9-02ea59f46af6.jpg)

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by rkpattnaik780** [comment]
> I would like to work on this issue

Go ahead. Assigning it to you.

**Comment by rkpattnaik780** [comment]
Before working on this issue you can checkout issues in the [Queue Management](https://github.com/coderwassananmol/BUB2/milestone/1). This issue is dependent on #42 and #43 .

**Comment by coderwassananmol** [comment]
@poojasrinivass Any updates on the issue?

**Comment by poojasrinivass** [comment]
Not yet. You can go ahead since I am stuck

**Comment by coderwassananmol** [comment]
> Not yet. You can go ahead since I am stuck

We are happy to help you. All you had to do was "ask".

**Comment by coderwassananmol** [comment]
@BhuwanChandra assigning this issue to you.

**Comment by coderwassananmol** [comment]
Please comment on this issue, so that I can assign it

**Comment by BhuwanChandra** [comment]
@coderwassananmol assign this issue to me.
