### ISSUE TITLE
Add a table to show the jobs of each type on queue listing page

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#45]
1. The table should contain two headers:
a) Job ID
b) Title

2. The data of the table will change upon clicking on the type of job (waiting, completed, delayed, failed).

3. The data will be taken from the Bull API. Documentation [here](https://github.com/OptimalBits/bull#documentation).

4. Default is waiting.

5. The title should link to "/queue/list/:jobid", where ":jobid" is a path parameter.

Note: You can use a plugin like "React Table" to accomplish this task.
Sample design:
![queue table](https://user-images.githubusercontent.com/12458972/75814140-3d799d00-5db7-11ea-9580-bd539ede149d.jpg)

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. please assign this to me.

**Comment by Parikshit-Hooda** [comment]
@BhuwanChandra go ahead. assigned.

**Comment by BhuwanChandra** [comment]
@coderwassananmol Is there any server-side endpoint to fetch data for table or I need to create the endpoint accordingly?

**Comment by coderwassananmol** [comment]
> @coderwassananmol Is there any server-side endpoint to fetch data for table or I need to create the endpoint accordingly?

No. There is no server-side endpoint as of now. You can create it.

**Comment by BhuwanChandra** [comment]
I am having trouble with docker and redis, getting these errors 

```

(node:41620) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (E:\Coding\BUB2\node_modules\ioredis\built\redis\index.js:283:31)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:41620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:41620) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (E:\Coding\BUB2\node_modules\ioredis\built\redis\index.js:283:31)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```
can you tell me how to fix these errors?
since, I have created the table but not able to fetch the data due to these error.

**Comment by coderwassananmol** [comment]
> I am having trouble with docker and redis, getting these errors
> 
> ```
> 
> (node:41620) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
>     at Socket.<anonymous> (E:\Coding\BUB2\node_modules\ioredis\built\redis\index.js:283:31)
>     at Object.onceWrapper (events.js:286:20)
>     at Socket.emit (events.js:198:13)
>     at Socket._onTimeout (net.js:442:8)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)
> (node:41620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:41620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:41620) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
>     at Socket.<anonymous> (E:\Coding\BUB2\node_modules\ioredis\built\redis\index.js:283:31)
>     at Object.onceWrapper (events.js:286:20)
>     at Socket.emit (events.js:198:13)
>     at Socket._onTimeout (net.js:442:8)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)
> ```
> 
> can you tell me how to fix these errors?
> since, I have created the table but not able to fetch the data due to these error.

Can you share your `redishost` and `redisport` environment variable? Can you verify if your docker container containing the redis service is running properly?

**Comment by BhuwanChandra** [comment]
redishost=docker
redisport=6379

and this is the docker-compose.yml file:
```
version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
```

**Comment by BhuwanChandra** [comment]
@coderwassananmol there are the same ids for two different jobs like the first job of pdl-queue and the first job of gb-queue has id 1, 2nd, 3rd... has 2, 3... etc. 
so, how to link them with jobid parameter?

**Comment by coderwassananmol** [comment]
> can I use bookid in jobid as it is unique for every book?

Yes, we can use bookid as a parameter. Or otherwise, we can use /queue/list/gb/:jobid to show for google books and similarly for pdl

**Comment by BhuwanChandra** [comment]
Ok then i will use /queue/list/q_name/:jobid for this
