### ISSUE TITLE
Store information in job logs for google books

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#46]
During upload from google books, we should use https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#joblog to store job logs. The information should be stored in stringified json with the following fields:
thumbnail uri, title, author, pages, internet archive link

This information will be used by the queue listing page and for listing a particular job.

**Comment by Ruchika30** [comment]
Can i work on it ? @coderwassananmol

**Comment by coderwassananmol** [comment]
Fixed in next release.
