### ISSUE TITLE
Store information in job logs for panjab digital library

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#47]
During upload from panjab library, we should use https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#joblog to store job logs. The information should be stored in stringified json with the following fields:
image uri, title, author, pages, internet archive link

This information will be used by the queue listing page and for listing a particular job.

**Comment by kichloo** [comment]
@coderwassananmol I would like to take up this issue and fix it, though I am a beginner.

**Comment by Parikshit-Hooda** [comment]
@kichloo attempt it! we are here to help.

**Comment by Parikshit-Hooda** [comment]
Let me know if you're interested and i'll assign it to you/

**Comment by kichloo** [comment]
@Parikshit-Hooda I only use Github to make these PRs and do the required changes (not Git Desktop or Git Bash), so if all this can be done using it, I am ready to work on the issue!

**Comment by coderwassananmol** [comment]
Completed via [cb76e03](https://github.com/coderwassananmol/BUB2/commit/cb76e03a7c1f8673a878a6d657919e987b6969be)
