### ISSUE TITLE
Separate instructions for BUB setup

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#49]
Setting up of the project is slightly different for different OSes. Different sections containing setup instructions for different OSes is requested.

**Comment by Parikshit-Hooda** [comment]
These sections need to be contained in the README.md itself.

**Comment by Medha-B** [comment]
I would like to work on this. Kindly assign me the issue and also provide some guidance on how to get started.

**Comment by Parikshit-Hooda** [comment]
@Medha-B go ahead.

**Comment by kavyashree1903** [comment]
I would like to work on this.

**Comment by coderwassananmol** [comment]
Not needed.
