### ISSUE TITLE
Change Panjab to Punjab

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#50]
Change type at all locations in the repo from Panjab to Punjab

**Comment by habeeba-naaz** [comment]
I am gssoc20 participant....I interested to do this

**Comment by Parikshit-Hooda** [comment]
Hi @habeeba-naaz I have added the 'taken' label. Please proceed. When you submit the PR, do reference this issue so that we can track it better. Thanks.

**Comment by habeeba-naaz** [comment]
Sure...thank you...changing documents do we need install anything or just change it and save

**Comment by Parikshit-Hooda** [comment]
fork edit PR should do. Just make sure you cover all instances. Should I assign this to you?

**Comment by habeeba-naaz** [comment]
Yes...please assign me

**Comment by Parikshit-Hooda** [comment]
Ok. Go forward.

**Comment by FrozenGirl-spd** [comment]
Can i work on the issue?
