### ISSUE TITLE
add 'request to contribute' section in readme

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#51]
To allow and receive requests and contributions, we should add 'contributing' section in the README.md. After writing necessary details there, we should redirect to CONTRIBUTING.md .

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by Parikshit-Hooda** [comment]
@poojasrinivass go ahead.

**Comment by Parikshit-Hooda** [comment]
@poojasrinivass Please update us within by tonight or we'll open this issue up for grabs again. If you need help, do ask us.

**Comment by poojasrinivass** [comment]
I'm working on it. Can you please give me time till tomorrow to make a PR?
