### ISSUE TITLE
Add contribution templates

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#52]
Add 'PR_TEMPLATE' and 'ISSUE_TEMPLATE' to the repo for more structured contributions.

**Comment by Parikshit-Hooda** [comment]
Consult [circuitverse templates](https://github.com/CircuitVerse/CircuitVerse/tree/master/.github)

**Comment by HarshCasper** [comment]
Can you please assign me this issue @Parikshit-Hooda I will be much obliged

**Comment by Parikshit-Hooda** [comment]
@HarshCasper done

**Comment by HarshCasper** [comment]
Kindly look into the Pull Request I have made @Parikshit-Hooda @coderwassananmol

**Comment by Parikshit-Hooda** [comment]
@coderwassananmol why do we have ISSE_TEMPLATE and .github/ISSUE_TEMPLATE in the root. This looks wrong to me. @HarshCasper please nest all issue_templates in the .github directory itself and make a PR.

**Comment by coderwassananmol** [comment]
The contribution templates have been created. Closing the issue.
