### ISSUE TITLE
search and fix all typos

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#53]
Search and fix all typos in the repo.

**Comment by nabeeljay** [comment]
I would like to work on this.

**Comment by Parikshit-Hooda** [comment]
@nabeeljay please proceed

**Comment by Parikshit-Hooda** [comment]
@FrozenGirl-spd this issue is 'taken' right now. If this issue remains open(meaning that @nabeeljay ) fails to submit a PR in a reasonable amount of time, you can take it up.

**Comment by Parikshit-Hooda** [comment]
@nabeeljay What's the progress on this issue. Please update us by tonight or we'll open this issue up for grabs again. If you need help, do ask us.

**Comment by Parikshit-Hooda** [comment]
@FrozenGirl-spd do you want to take up this issue?

**Comment by sharmakeshav10** [comment]
I would like to work on this issue. @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
@sharmakeshav10  okay. Just go through the entire repo, find the typos(you may use a software, like Grammarly, to assist in finding language errors), fix them and raise a PR detailing all the typos you have fixed. 
*Don't change Panjab to Punjab* while you fix the typos.

**Comment by coderwassananmol** [comment]
Issue is up for grab again!

**Comment by kichloo** [comment]
@Parikshit-Hooda @coderwassananmol I can take us the issue!

**Comment by FrozenGirl-spd** [comment]
Yes! I want to work on this issue. Can you please assign this to me?!! @Parikshit-Hooda

**Comment by shreyakapoor08** [comment]
@Parikshit-Hooda can I work on this issue ?

**Comment by Parikshit-Hooda** [comment]
@shreyakapoor08 we're gonna remove the 'gssoc' label(meaning this issue can't be graded). so, it's wise to find a different issue. please check 19 march's slack messages on the gssoc group.

**Comment by kichloo** [comment]
@Parikshit-Hooda But I submitted a PR for the issue yesterday.

**Comment by Parikshit-Hooda** [comment]
Hi. please refer to this issue in your PR, by midnight.

**Comment by kichloo** [comment]
@Parikshit-Hooda Done.
