### ISSUE TITLE
Add 'instructions for gssoc' section in README.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#54]
Add 'instructions for gssoc' file to the repo.
The intention of this issue is to solve the redundant queries asked about gssoc by the participants. For example, the working of 'taken' label. the guidelines to follow for contribution under gssoc.

**Comment by HarshCasper** [comment]
Can you please assign me this issue @Parikshit-Hooda I will be much obliged

**Comment by Parikshit-Hooda** [comment]
@HarshCasper done

**Comment by Parikshit-Hooda** [comment]
@HarshCasper  Please update us by tonight or we'll open this issue up for grabs again. If you need help, do ask us.

**Comment by HarshCasper** [comment]
@Parikshit-Hooda I will complete it by midnight. Due to some College Work, I was going under heavy workload. I will finish the Issue requirements today.

**Comment by shreyakapoor08** [comment]
@Parikshit-Hooda can i work on this?

**Comment by kichloo** [comment]
@Parikshit-Hooda Being a beginner, can I work on this?

**Comment by coderwassananmol** [comment]
@shreyakapoor08 and @kichloo Please submit a PR. The one who submits it first, shall be considered.

**Comment by kichloo** [comment]
@coderwassananmol The instructions are to be added to the README.md, as mentioned?

**Comment by Parikshit-Hooda** [comment]
@kichloo i recommend making a separate file in the project root directory called something like 'GSSOC_INSTRUCTIONS.md'. This will help us keep readme short and concise and we can later remove the instructions file at our will.

**Comment by kichloo** [comment]
@Parikshit-Hooda Thanks for the input. And I want to just ask one more question. Should I add the FAQs from GSSOC website though it contains some points before selection also.

**Comment by kichloo** [comment]
@Parikshit-Hooda Created instructions.md!

**Comment by shreyakapoor08** [comment]
@Parikshit-Hooda should I make a separate PR for it ?

**Comment by Parikshit-Hooda** [comment]
@shreyakapoor08 @kichloo kichloo has made a PR already. I have posted a review on his PR. If the PR is abandoned, you can raise a PR(follow up on this issue in 3 days, thanks.)

**Comment by coderwassananmol** [comment]
Since GSSoC is over, closing this issue.
