### ISSUE TITLE
Add FAQ section to BUB

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#55]
Add faq section to README.md . This would be an open issue for some time where new FAQs would be added to repo. After some FAQs(max 5), redirect to a FAQ.md file in the repo.

**Comment by Parikshit-Hooda** [comment]
Things to address: topics to cover in FAQs, mentioning this issue as a point/place to propose new FAQs.

**Comment by nabeeljay** [comment]
I would like to work on it.

**Comment by Parikshit-Hooda** [comment]
@nabeeljay Please go ahead. I have assigned it to you.

**Comment by Parikshit-Hooda** [comment]
@nabeeljay What's the progress on this issue? Please respond with the progress or we'll unassign you and make this issue up for grabs again. Thanks.

**Comment by habeeba-naaz** [comment]
I am interested to work on this...please assign me

**Comment by shreyakapoor08** [comment]
Hey, I want to work on this issue

**Comment by dvitiarora** [comment]
I am interested in working on this issue. Please assign it to me.

**Comment by Parikshit-Hooda** [comment]
@habeeba-naaz make a FAQ.md . @habeeba-naaz @shreyakapoor08 @dvitiarora please discuss all the FAQs here before going for the PR. I am gonna assign all three of you. Also, do update us on the progress within 3 days or I assign all three of you.

**Comment by habeeba-naaz** [comment]
Sure...thank you for assigning

**Comment by shreyakapoor08** [comment]
got it

**Comment by dvitiarora** [comment]
Okay, thank you for assigning.

**Comment by habeeba-naaz** [comment]
**What is Book Uploader Bot?**
 A Book Uploader Bot transfers documents from public libraries such as Google Books, and Punjab Digital Library etc to Internet Archive.
**What is Wikimedia Tool Labs?** -Please answer
**What are the Prerequisites?**
 NodeJs,Docker ToolBox,Redis
**What is the purpose of NodeJs,Docker ToolBox and Redis in this project?** Please answer
**What is the Tech stack of this project?** 
Javascript,React Js and Node Js
**How are you implementing this system?** Please answer
**Do you have Website?** Please answer
**Do you have app?** Please answer
**What are the future enhancements?**Please answer


These are some FAQ's i thought ...please let me know any changes to be done? @Parikshit-Hooda

**Comment by shreyakapoor08** [comment]
Is the website paid?
Why Book uploader bob is needed?

these can also be added

**Comment by dvitiarora** [comment]
1. Can I upload my own book?
Ans: (*please tell if this is allowed or not.)
Yes, it can be done by uploading your book to google books and then provide the link.

2. Can I delete or undo an upload?
Ans: (*Please answer.)

3. Which languages and what categories of books can be uploaded?
Ans: There is no restriction on language. Books of all languages are supported and can be uploaded using BUB (*please tell if other categories like journals, articles, etc can be uploaded or not, along with books?)

4. How can I contact for more queries?
Ans: E-mail ID or any other contact(*please specify)

Please review these too, @Parikshit-Hooda

**Comment by shreyakapoor08** [comment]
> @habeeba-naaz make a FAQ.md . @habeeba-naaz @shreyakapoor08 @dvitiarora please discuss all the FAQs here before going for the PR. I am gonna assign all three of you. Also, do update us on the progress within 3 days or I assign all three of you.

Should I start working on it if you approve?

**Comment by Parikshit-Hooda** [comment]
answer to:
1. if an appropriate license is attached to the book which allows it to be archived(which doesn't allow copyright infringement suits, etc.)
2. archives are supposed to be read-only, and deleting is a 'write' operation, so i think no.
4. open an issue on this repo.
@coderwassananmol please approve.

**Comment by habeeba-naaz** [comment]
Thank you @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
raise a PR by midnight please.

**Comment by Parikshit-Hooda** [comment]
combine all the questions in this issue.

**Comment by habeeba-naaz** [comment]
Okay
