### ISSUE TITLE
Design BUB logo

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#56]
Design logo for the project.

**Comment by Xtremilicious** [comment]
Would like to work on this!

**Comment by rkpattnaik780** [comment]
That would be great @Xtremilicious . Go ahead!

**Comment by Xtremilicious** [comment]
Thanks for assigning to me! First of all. I need some info regarding the logo.
1. Any colour scheme you have in mind?
2. Any suggestions regarding the initial design?

**Comment by Parikshit-Hooda** [comment]
@Xtremilicious Go crazy. We don't have any logo right now, so what you design will obviously require iterations. Also, please respond with the progress or we'll unassign you and make this issue up for grabs again. Thanks.

**Comment by Xtremilicious** [comment]
@Parikshit-Hooda Sure, here's the design I made till now.

![draft1](https://user-images.githubusercontent.com/47635607/76210646-89e73180-622a-11ea-9355-3db7d3a116f0.png)
![draft2](https://user-images.githubusercontent.com/47635607/76210650-8c498b80-622a-11ea-9893-a1f066b37146.png)

**Comment by rkpattnaik780** [comment]
This looks good to me! I will personally prefer the second logo. Seeing #68 , I feel we are going to use a lot of Blue. Any opinions @Parikshit-Hooda @coderwassananmol ?

**Comment by Xtremilicious** [comment]
@Parikshit-Hooda @rkpattnaik780 @coderwassananmol Let me know your suggestions:)

**Comment by Parikshit-Hooda** [comment]
the second one is better because the blue book will align with wikimedia's color scheme? We'll need a favicon as well. Could you design a similar one(and minimalistic) design for the favicon as well? If yes, please open an issue for the favicon logo design.

**Comment by Xtremilicious** [comment]
@Parikshit-Hooda I'd love to design a favicon as well. Kindly finalise the design for this issue and instruct me how to close this one :)

**Comment by coderwassananmol** [comment]
> @Parikshit-Hooda Sure, here's the design I made till now.
> 
> ![draft1](https://user-images.githubusercontent.com/47635607/76210646-89e73180-622a-11ea-9355-3db7d3a116f0.png)
> ![draft2](https://user-images.githubusercontent.com/47635607/76210650-8c498b80-622a-11ea-9893-a1f066b37146.png)

Thanks for your effort. The design looks great. Few suggestions:
1. Include the name "Book Uploader Bot" in your logo.
2. Have a "Powered by: " footer with two logos:
a) https://wikitech.wikimedia.org/wiki/File:Toolforge_logo.svg
b) https://commons.wikimedia.org/wiki/File:Wikimedia_Foundation_Logo.png
3. The robot in the back doesn't seem right. Can we skip it or think of something else?

**Comment by Xtremilicious** [comment]
Thanks for the suggestions. Here is the logo after the changes :)
![BUB](https://user-images.githubusercontent.com/47635607/76465654-17ce4280-640c-11ea-937c-26b26a1b2a35.png)

**Comment by rkpattnaik780** [comment]
Looks good to me, you can raise a PR I guess.

**Comment by Parikshit-Hooda** [comment]
@Xtremilicious To close this issue, I think that you should place this logo on the README.md top, like https://github.com/CircuitVerse/CircuitVerse/blob/master/README.md and raise a PR. For the favicon, you should simplify the current design so that it is distinct and neat when we indeed use it as a favicon. @rkpattnaik780 I think we should open a separate issue to locate the logo on the app website or do we do it under this issue only?

**Comment by Xtremilicious** [comment]
@Parikshit-Hooda I'll do a PR soon. Kindly open another issue for the favicon and assign it to me so that I can submit the favicon as well :)

**Comment by rkpattnaik780** [comment]
@Xtremilicious , the issue for favicon is #87 .
