### ISSUE TITLE
Search more sources for books

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#57]
Search more books sources from where they can be added to the Internet archive. at this time, supported : punjab digital library and google books.
The list of prospective sources could be added as 'Help Wanted' so that developers could develop bub to support the new sources for books too.

**Comment by pundreek-saurabh** [comment]
I'll be happy to contribute on this issue.

**Comment by Parikshit-Hooda** [comment]
@pundreek-saurabh please proceed.

**Comment by Parikshit-Hooda** [comment]
@pundreek-saurabh  What's the progress on this issue? Please respond with the progress or we'll unassign you and make this issue up for grabs again. Thanks.

**Comment by pundreek-saurabh** [comment]
Hey there !! Currently I'm in the region with almost no internet coverage
so I'll not be able to contribute anything in this project till 16th of
march . Then after I'll be available for it upto last date  . I'm so sorry
for the inconvenience . Please consider my situation and provide me
confirmation regarding this .

**Comment by dvitiarora** [comment]
Hey, I am interested in working on this.

**Comment by Parikshit-Hooda** [comment]
@dvitiarora go ahead. please update us within 3 days.

**Comment by dvitiarora** [comment]
Okay, thank you for assigning.

**Comment by dvitiarora** [comment]
@Parikshit-Hooda can we upload articles, journals, thesis, etc. through BUB. Like, should I include sources where articles and journals can be found and added to the Internet Archive?

**Comment by coderwassananmol** [comment]
> Other sources:
> (*I have provided link of the website along with the sample link of a book available on the site)
> 
> 1. Project Gutenberg(https://www.gutenberg.org/)
>    Sample Link: http://www.gutenberg.org/files/155/155-h/155-h.htm
> 
> 2.Open Book Publishers(https://www.openbookpublishers.com/)
> Sample Link: https://www.openbookpublishers.com/product/106#0
> 
> 3.Bookrix(https://www.bookrix.com/)
> Sample Link: https://www.bookrix.com/book.html?bookID=bx.shakespeare_1212071424.7241220474#3240,540,94606
> 
> 1. Library of Congress  (http://www.read.gov/books/)
>    Sample Link: http://www.read.gov/books/pageturner/aesops_fables/#page/8/mode/2up
> 2. ManyBooks(https://manybooks.net/)
>    Sample Link: [https://manybooks.net/book/139515/read#epubcfi(/6/2[titlepage]!/4/1:0)](https://manybooks.net/book/139515/read#epubcfi(/6/2%5Btitlepage%5D!/4/1:0))
> 3. Bloomsbury Collections(https://www.bloomsburycollections.com/)
>    Sample Link of Book: https://www.bloomsburycollections.com/book/government-communication-cases-and-challenges/#0
> 4. Directory of Open Access Journals(https://doaj.org/)
>    Sample Link: https://doaj.org/article/5b3b17834afa41848e52db56c0c9ea78#0
> 
> @Parikshit-Hooda please review these sources and let me know if there is a need for any correction.
> Also, can we upload articles, journals, thesis, etc. through BUB?

These are good sources. Can you also verify which of them have public APIs available?

**Comment by dvitiarora** [comment]
Okay, can you provide any hints regarding how to check if public APIs are available for a particular website or not?
