### ISSUE TITLE
add LICENSE.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#58]
Add appropriate license file to the project.
Proposal : In the LICENSE file that is added, change copyright timeline from '20xx - **present**'

**Comment by HarshCasper** [comment]
Can you please assign me this issue @Parikshit-Hooda I will be much obliged to work on this issue.

**Comment by Parikshit-Hooda** [comment]
Sure. Go on. Talk on slack about what license file is needed. Suggest a license from your knowledge or find related projects and see if the license in their project applies to our case too. Thanks.

**Comment by coderwassananmol** [comment]
@HarshCasper Any updates on the issue?

**Comment by HarshCasper** [comment]
I have added the LICENSE file. Kindly look into it @coderwassananmol @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
@HarshCasper Why have you used this license?

**Comment by rajat2502** [comment]
I guess this issue is already fixed in #70
