### ISSUE TITLE
Produce YouTube videos for BUB

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#59]
I propose Youtube videos for BUB. Topics to cover:
- installing bub project
- using bub for uploading books
- running bub for development/contributions
- project outreach purposes

The videos could be screen recordings with voice-over. I am happy to help on the production front.

**Comment by CSElonewolf** [comment]
The issue looks interesting.I would like to work on this.With little help from your side dear mentor I would be able to complete it.Sir you can assign me the task.

**Comment by Parikshit-Hooda** [comment]
Sure, go ahead. Assigned, Help asked is help received. @CSElonewolf

**Comment by Parikshit-Hooda** [comment]
@CSElonewolf  What's the progress on this issue? Please respond with the progress or we'll unassign you and make this issue up for grabs again. Thanks.

**Comment by CSElonewolf** [comment]
Sorry I unassigned myself.Because untill and unless the issue #66 is solved the youtube video can't be recorded.As a lot of buttons gets misplaced and there is a footer issue when the site is opened :(

**Comment by Parikshit-Hooda** [comment]
@CSElonewolf will try to resolve #66 and then we'll see to this.

**Comment by coderwassananmol** [comment]
Not required anymore.
