### ISSUE TITLE
Remove the deprecation warnings

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#6]
A few deprecation warnings arrive while using the tool. We need to get rid of them.

**Comment by Nikhil-Kumaran** [comment]
Hey @coderwassananmol 
Did you mean the depreciation warning during npm install? 

![Screenshot 2019-10-07 at 7 36 38 PM](https://user-images.githubusercontent.com/25131835/66318968-eb346d00-e939-11e9-8bff-b8af6579a2c3.png)

If not can you give more context and post a screenshot if possible?

**Comment by coderwassananmol** [comment]
Yes. But when you use the application, you will find a few deprecation warnings like using Buffer etc. Search for all the possible deprecation warnings and change the code if necessary.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me fo GSSoC'20.

**Comment by TeAmP0is0N** [comment]
I would like to work on this issue.

**Comment by Major2001** [comment]
@coderwassananmol  I would like to work on this issue

**Comment by coderwassananmol** [comment]
Feel free to add PR

**Comment by coderwassananmol** [comment]
Anyone interested in working on this issue?

**Comment by dvitiarora** [comment]
I would like to work on this issue.

**Comment by kichloo** [comment]
@coderwassananmol I would like to work on it but I am a beginner.

**Comment by Parikshit-Hooda** [comment]
@kichloo do you want to work on this? Please let us know so that we can help. This is a good issue for you, in my opinion.

**Comment by Parikshit-Hooda** [comment]
It's not related to git-bash per se. When you run the app via 'npm run dev' or 'npm run start', you should get these warnings.

> Yes. But when you use the application, you will find a few deprecation warnings like using Buffer etc. Search for all the possible deprecation warnings and change the code if necessary.

**Comment by Dishebh** [comment]
I would like to work on this issue? Can I take it?

**Comment by coderwassananmol** [comment]
Migrated to https://phabricator.wikimedia.org/T344116
