### ISSUE TITLE
Add 'examples' section in README

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#60]
Add 'examples' section in README so that users/developers can understand how the software works via examples.

**Comment by samridhijain27** [comment]
I would like to work on this. Can you assign this to me ?

**Comment by Parikshit-Hooda** [comment]
Ok @samridhijain27 . Go ahead.

**Comment by coderwassananmol** [comment]
@samridhijain27 Any updates?

**Comment by samridhijain27** [comment]
I am working on that one. fell sick . So thats why delayed. Will update you by EOD.

**Comment by samridhijain27** [comment]
Thanks for reassigning this to me!

**Comment by Parikshit-Hooda** [comment]
@samridhijain27 updates?

**Comment by shreyakapoor08** [comment]
hey, can i take up this issue?

**Comment by samridhijain27** [comment]
I am working on this issue, facing bit of time constraints. Will try to close this ASAP. Sorry about the delay.

**Comment by Kuljeet-123** [comment]
@shreyakapoor08 can I work on this issue.

**Comment by coderwassananmol** [comment]
Issue is up for grab again!

**Comment by shreyakapoor08** [comment]
> Issue is up for grab again!

can I work on this issue? @coderwassananmol

**Comment by Kuljeet-123** [comment]
@coderwassananmol @shreyakapoor08 I'm a GSSOC'20 participant I want to work on this issue.

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 go ahead, will assign it to you.

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda I have One doubt do I have to show example of how to upload the books or I have to show all books uploaded through the BUB2.

**Comment by Parikshit-Hooda** [comment]
the former one. To help people know how its done.

> Add 'examples' section in README so that users/developers can understand how the software works via examples.

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda I have raised the PR...Please review it and merge it.
