### ISSUE TITLE
explain software architecture via block diagram

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#61]
I think we should include an image which shows the architecture of BUB via a block diagram. Goal: summarized view of software, better understandability.

**Comment by poojasrinivass** [comment]
I would like to work on this issue. @Parikshit-Hooda Could you please assign this issue to me

**Comment by Parikshit-Hooda** [comment]
Ok. Go ahead. @poojasrinivass

**Comment by coderwassananmol** [comment]
@poojasrinivass Any updates?

**Comment by preeti13456** [comment]
Interested

**Comment by Parikshit-Hooda** [comment]
@preeti13456 assigned. Please update us on your own after 3 days or submit a PR, whichever is sooner. Thanks.

**Comment by coderwassananmol** [comment]
Issue is up for grab again!

**Comment by abhu-A-J** [comment]
@coderwassananmol I'm interested in the issue. Do we have the architecture details somewhere so that I make a block diagram out of it?? I'm not versed with the project.

**Comment by coderwassananmol** [comment]
> @coderwassananmol I'm interested in the issue. Do we have the architecture details somewhere so that I make a block diagram out of it?? I'm not versed with the project.

Our front-end is powered with React and Next.js. For server side, we use Node.js. For Queue Management system, we use Bull which internally calls out Redis server to store information. Currently, we support two libraries, PDL and GB. For each library, we have separate consumer and producer. There is another service, i.e., the email service that sends email upon success/failure of the uploading of book. It also has its separate producer and consumer.
For other details, I'd ask you to go through the code and figure it out. :)
I have explained you in a nutshell.

**Comment by abhu-A-J** [comment]
> > @coderwassananmol I'm interested in the issue. Do we have the architecture details somewhere so that I make a block diagram out of it?? I'm not versed with the project.
> 
> Our front-end is powered with React and Next.js. For server side, we use Node.js. For Queue Management system, we use Bull which internally calls out Redis server to store information. Currently, we support two libraries, PDL and GB. For each library, we have separate consumer and producer. There is another service, i.e., the email service that sends email upon success/failure of the uploading of book. It also has its separate producer and consumer.
> For other details, I'd ask you to go through the code and figure it out. :)
> I have explained you in a nutshell.

@coderwassananmol It is a lot harder than I thought. I think I'll look at some easier issues to get started. You can assign someone lse this issue

**Comment by greyhatlinux** [comment]
hey @coderwassananmol 
I would love to take up the task :smile:

**Comment by ishukhanchi** [comment]
Can we make this using a UML diagram?

**Comment by Parikshit-Hooda** [comment]
@ishukhanchi it should be embeddable in the readme. If its possible, we can do UML too. Maybe the UML can be converted to jpg png too, if uml is not embeddable.

**Comment by ishukhanchi** [comment]
Yeah, a png/jpeg file can be made.I'll do it.

**Comment by Parikshit-Hooda** [comment]
@ishukhanchi go ahead.

**Comment by Parikshit-Hooda** [comment]
@ishukhanchi what's the progress?

**Comment by ishukhanchi** [comment]
I'm on it. Will update once done.

**Comment by ishukhanchi** [comment]
![uml](https://user-images.githubusercontent.com/28891982/82123007-a10b4800-97b4-11ea-86bf-d529c0ca7789.png)

Please check this once.

**Comment by Parikshit-Hooda** [comment]
I think @coderwassananmol should review this diagram.

**Comment by ishukhanchi** [comment]
Till then I'll try to complete it.

**Comment by coderwassananmol** [comment]
@ishukhanchi This UML diagram sort of demonstrates what the tool does. We want a diagram that would go into technical details of how the book uploading and queue service takes place. Read my above comment: https://github.com/coderwassananmol/BUB2/issues/61#issuecomment-602249992 to get to know what kind of details I am looking for. All the best!

**Comment by ishukhanchi** [comment]
![uml](https://user-images.githubusercontent.com/28891982/82292984-6a5a4b00-99c9-11ea-927a-aeff00fd58c6.png)
Kindly review this one.

**Comment by coderwassananmol** [comment]
Thanks @ishukhanchi . Closing the issue.
