### ISSUE TITLE
Add badges to the repo

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#62]
Add appropriate badges to the repo for an overall good project. 
Task:
- research different badges(services to be integrated) that can be applied. Check which of these can be implemented right away. Discuss on this issue's comments section with contributors to finalise the badges.
Example of badges:
![Capture1](https://user-images.githubusercontent.com/25405707/75952431-bd495980-5ed4-11ea-81e6-288a4b6faddd.PNG)
![Capture2](https://user-images.githubusercontent.com/25405707/75952432-be7a8680-5ed4-11ea-82c1-805a82d2c899.PNG)

**Comment by arghac14** [comment]
Can i work on this?

**Comment by Parikshit-Hooda** [comment]
yes, you can. I suppose you are a gssoc participant?

**Comment by Parikshit-Hooda** [comment]
@arghac14 Please let me know if you aren't a gssoc participant. I haven't assigned to you issue yet. Without this info, I won't assign it to you.

**Comment by arghac14** [comment]
@Parikshit-Hooda yes I'm a gssoc participant, please assign me this

**Comment by Parikshit-Hooda** [comment]
Ok @arghac14 Please proceed. I have assigned it to you.

**Comment by arghac14** [comment]
@Parikshit-Hooda I'm thinking to add few general badges like
**Github licence**, **version**, **dependency**, **download count**, **forks count**, **stars count** **issues count**, **pull requests count** , **contributors count** etc and few community badges like maillist, slack(would require the links if this project has any community platforms) and few other badges. 

If you have any other badge suggestions or if these are enough, please let me know here!
And, also provide the links of the slack channel or any other platform like telegram or any maillist if that is required!

**Comment by coderwassananmol** [comment]
> @Parikshit-Hooda I'm thinking to add few general badges like
> **Github licence**, **version**, **dependency**, **download count**, **forks count**, **stars count** ,**issues count**, **pull requests count** , **contributors count** etc and few community badges like maillist, slack(would require the links if this project has any community platforms) and few other badges.
> 
> If you have any other badge suggestions or if these are enough, please let me know here!
> And, also provide the links of the slack channel or any other platform like telegram or any maillist if that is required!

These badges would do!
