### ISSUE TITLE
Improve  the Responsiveness of the website https://bub2.toolforge.org/

### ISSUE THREAD

**Issue by CSElonewolf** [coderwassananmol/BUB2#66]
1. Correct the position of the Enter E-mail input field under the Upload Tab

2. Correct the position of the Card Section under the Queues Tab.

Please assign me this task

**Comment by coderwassananmol** [comment]
> 1. Correct the position of the Enter E-mail input field under the Upload Tab
> 2. Correct the position of the Card Section under the Queues Tab.
> 
> Please assign me this task

Thanks for reporting the issue. Please find the below scope for completing the issue:
1. Improving the homepage (including fields, header and footer) on mobile
2. Improving the queue page (cards and footer)

Assigning it to you. All the best.

**Comment by CSElonewolf** [comment]
It looks like the whole codebase for the site is on REACT. But I have no working experience on REACT.
But I can improve UI of the site completely using HTML,CSS,Bootstrap 4.
Shall I proceed?

**Comment by coderwassananmol** [comment]
> It looks like the whole codebase for the site is on REACT. But I have no working experience on REACT.
> But I can improve UI of the site completely using HTML,CSS,Bootstrap 4.
> Shall I proceed?

You don't need react for responsiveness. Go ahead! :)

**Comment by CSElonewolf** [comment]
@coderwassananmol hello sir I am done with the responsiveness...Please check the change in this site
[bub2-demo](https://bub2.netlify.com/)

![Screenshot_2020-03-08-14-28-54-184_com android browser](https://user-images.githubusercontent.com/51082429/76159760-a3647c80-6149-11ea-8a71-71e214554826.png)
![Screenshot_2020-03-08-14-28-30-512_com android browser](https://user-images.githubusercontent.com/51082429/76159763-a7909a00-6149-11ea-9fa9-b65255d22df0.png)

**Comment by coderwassananmol** [comment]
Issue is up for grab again!

**Comment by Xtremilicious** [comment]
Interested!

**Comment by coderwassananmol** [comment]
> Interested!

Assigned to you!
