### ISSUE TITLE
Show book preview after user adds Google Books ID

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#7]
Currently, we only show the book title and steps. It would be nice to show book cover image as well.

**Comment by itsthecheat** [comment]
Hi @coderwassananmol, would love to take this on

**Comment by coderwassananmol** [comment]
Feel free! :)

> Hi @coderwassananmol, would love to take this on

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me fo GSSoC'20.

**Comment by Major2001** [comment]
@coderwassananmol I want to work on this issue

**Comment by LMPerera** [comment]
I would like to work on this issue

**Comment by coderwassananmol** [comment]
Feel free to add PR.

**Comment by coderwassananmol** [comment]
Anyone interested on working on this issue?

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. please assign this to me.

**Comment by dipanshuraz** [comment]
I am interested @coderwassananmol

**Comment by ankitjena** [comment]
Go ahead @dipanshuraz . Please make PR

**Comment by ankitjena** [comment]
Follow up on #119 and #120
