### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by rajat2502** [coderwassananmol/BUB2#76]
Add a new file namely CODE_OF_CONDUCT.md that contains the standards, scope and other responsibilities like reporting violations and conflict resolution.

For reference see: https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md

**Comment by shreyakapoor08** [comment]
Hey, can i take up this issue?

**Comment by rajat2502** [comment]
@shreyakapoor08 Sure!!! Go ahead with the issue.

**Comment by shreyakapoor08** [comment]
@rajat2502 hey I have raised the PR. Kindly check and let me know if there is any corrections.
