### ISSUE TITLE
Add a issue template file 

### ISSUE THREAD

**Issue by rajat2502** [coderwassananmol/BUB2#77]
Add a new file namely issue_template.md.
This file should be located as `.github/ISSUE_TEMPLATE/issue_template.md`.

For any guide or help please refer to https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

**Comment by adityabisoi** [comment]
I can do this Please assign it to me.

**Comment by rajat2502** [comment]
@adityabisoi Yeah Sure, Go Ahead!!!
