### ISSUE TITLE
Wireframe/design for stats page

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#79]
We have a wireframe for the homepage. A similar design pattern has to follow for the /stats page as well.
@guptavarun619 You might wanna take this up.

**Comment by guptavarun619** [comment]
Sure, but can get a little bit information about the page?

**Comment by coderwassananmol** [comment]
Sure. This route displays statistical information for BUB2.
1. The queue for Google Books (active jobs, waiting jobs etc.)
2. The queue for Panjab Digital Library
3. Number of books uploaded to the Internet Archive
Currently, the UI is very simple with two cards.
Moving forward, we can keep the cards, if you want. But I am expecting same background colour as of homepage, compatible card background and with a little animation on it.
Here's a sample design:
![New Doc 2020-03-12 01 12 40](https://user-images.githubusercontent.com/12458972/76457515-f2870780-63fe-11ea-840c-8ebfddcca16b.jpg)

Don't forget to use developer-friendly fonts.

**Comment by guptavarun619** [comment]
Okay I'll get into this ASAP. please assign me this issue. P.S. Is "nunito" font acceptable "roboto" is used everywhere so it's kind of repetitive. Thanks for such details.

**Comment by coderwassananmol** [comment]
> Okay I'll get into this ASAP. please assign me this issue. P.S. Is "nunito" font acceptable "roboto" is used everywhere so it's kind of repetitive. Thanks for such details.

There has to be consistency with the fonts project-wide. I am looking for Lato/Raleway/Montserrat for the headings. Roboto/Fira Code/Open Sans for the normal texts.
