### ISSUE TITLE
Show book preview and confirmation after user adds Panjab Digital Library URL

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#8]
Currently, we only show the user confirmation text. We need to show him a preview where he/she can see the information of book and a confirmation button should be displayed. After the user clicks on the button, only then the book should be uploaded.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me fo GSSoC'20.

**Comment by LMPerera** [comment]
https://github.com/coderwassananmol/BUB2/issues/29

**Comment by BhuwanChandra** [comment]
@coderwassananmol I would like to work on this issue. Please assign this to me.

**Comment by rajat2502** [comment]
@shreyasrivastava936 Go Ahead and keep us updated about your progress.

**Comment by shreyasrivastava936** [comment]
@rajat2502  yeah sure

**Comment by coderwassananmol** [comment]
@shreyasrivastava936 Please provide updates on the issue. If you are stuck somewhere, we'll be happy to help!

**Comment by coderwassananmol** [comment]
Removing the "taken" flag due to inactivity.

**Comment by IuliaElizaS** [comment]
hello, 
I'm a gssoc20 participant and I would like to give it a try

**Comment by ankitjena** [comment]
Follow up on #121 and #120
