### ISSUE TITLE
Include LICENSE section in README.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#80]
Include LICENSE section in README.md . Copy the 'Contributing' section in the README.md for the LICENSE as well.

**Comment by poojasrinivass** [comment]
I would like to work on this issue.

**Comment by sharmakeshav10** [comment]
@Parikshit-Hooda I would like to work on this issue. Please assign me this.

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda  I would love to work on this issue ....can you please assign me this.

**Comment by Parikshit-Hooda** [comment]
@sharmakeshav10 @Kuljeet-123 @poojasrinivass whoever raises the PR first, wins. I am going to assign all three of you to this. A bit rash but RACE TO THE FINISH!

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda  I have created the PR....Please review it and merge it.

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 ok

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 please mention this issue in the PR so that we can refer to it. this will help in maintaining a chain. Just do something like 'fixes #80' in the PR comments. THanks.

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 please raise a PR to this repo. The current PR is merging from your 'LICENSE' branch to your 'develop' branch only. You need to merge it into your 'develop' branch and then raise a PR to merge your 'develop' branch into this repo's 'develop' branch. Thanks.

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda  I have raised the PR according to your guidelines...Please review it.

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 got it. have approved, waiting for the second review. will merge when done. Thanks for this!

**Comment by Kuljeet-123** [comment]
@Parikshit-Hooda  tysm .

**Comment by Parikshit-Hooda** [comment]
@Kuljeet-123 thanks.
