### ISSUE TITLE
add favicon file

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#87]
design and add favicon file.

**Comment by ishukhanchi** [comment]
Interested.

**Comment by rkpattnaik780** [comment]
This issue should be solved in accordance with #50.

**Comment by Xtremilicious** [comment]
@rkpattnaik780 Kidnly assign me. Thanks :)

**Comment by Xtremilicious** [comment]
Kindly have a look. Removed the texts and generated different sizes for different browsers and devices:

<img width="839" alt="ScreenShot_20200318013557" src="https://user-images.githubusercontent.com/47635607/76897217-53a85280-68b9-11ea-84c4-f481b32e5ed5.png">


![android-chrome-192x192](https://user-images.githubusercontent.com/47635607/76897281-76d30200-68b9-11ea-962a-920a9cd95126.png)

Let me know your suggestion :)

**Comment by rkpattnaik780** [comment]
@Xtremilicious it looks good to me

**Comment by dulcetsoul** [comment]
Is this issue closed?

**Comment by Xtremilicious** [comment]
Cool. kindly guide me where to put the icons (in which directory). Thanks.

**Comment by Parikshit-Hooda** [comment]
@Xtremilicious please do. put the faivcon file in assets directory and link to it at appropriate places. thanks1
