### ISSUE TITLE
Write unit test cases

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#9]
We don't have any unit test cases yet but we need them for future testing. You can use any library you wish. Write unit test cases for each function.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by coderwassananmol** [comment]
Feel free to submit a PR!

**Comment by ankitjena** [comment]
@vipuldcoder Are you working on this?

**Comment by Parikshit-Hooda** [comment]
@vipuldcoder Are you working on this?

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSoC'20.

**Comment by coderwassananmol** [comment]
Migrated to https://phabricator.wikimedia.org/T344117
