### ISSUE TITLE
Add 'open book publishers' to 'choose the library'

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#96]
Add the 'open book publishers' option to 'choose the library' dropdown. The concerned dropdown is available on the website home page 'https://bub2.toolforge.org/' / 'http://localhost:5000/ '

**Comment by Aman-Codes** [comment]
I am a GSSOC participant and I would like to work on this issue. Please assign me this issue.

**Comment by ankitjena** [comment]
Sure @Aman-Codes , Go ahead
