### ISSUE TITLE
Update 'template id' for Open Book Publishers

### ISSUE THREAD

**Issue by Parikshit-Hooda** [coderwassananmol/BUB2#97]
Study the API structure of Open Book Publishers(obp) and update the templated input(point 2 in website).

Find the [templated obp API here](https://github.com/coderwassananmol/BUB2/blob/develop/HELP_WANTED.md#2-open-book-publishers)

The referred PR should result in integration of the 'id template' for obp.

**Comment by Bhanu-mbvg** [comment]
Hey, Can I work on this issue?

**Comment by dipanshuraz** [comment]
assign me

**Comment by Parikshit-Hooda** [comment]
@dipanshuraz @Bhanu-mbvg both of you go ahead. The first one to raise the PR gets the merege.

**Comment by Parikshit-Hooda** [comment]
@dipanshuraz @Bhanu-mbvg please update us. This is an easy issue.

**Comment by Parikshit-Hooda** [comment]
@dipanshuraz @Bhanu-mbvg if anyone of you has made some progress on this, please raise a PR to let me know. Till then, both of you remain unassigned.

**Comment by Garima-189** [comment]
Can I work on it?

**Comment by rampantRami** [comment]
yes

**Comment by dibakar95** [comment]
Can I work on this issue #GSSOC20

**Comment by Parikshit-Hooda** [comment]
I think garima is on it. you can look for others labeled gssoc. @Garima-189 please update us within 3 days with the PR.

**Comment by Parikshit-Hooda** [comment]
@rkpattnaik780 please handle this issue.

**Comment by Parikshit-Hooda** [comment]
@dibakar95 if you want you can work on this issue now. please comment here if you're interested so that we can assign it to you.

**Comment by ishukhanchi** [comment]
If it hasn't been assigned. I would like to work on this issue.

**Comment by dibakar95** [comment]
Please assign it to someone else. I can't right now. @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
ok. @ishukhanchi i am assigning it to you now.

**Comment by Parikshit-Hooda** [comment]
currently. if you go to https://bub2.toolforge.org/ , and then click on 'help' button on top-right corner of the webapp, then click on the 'faq' in the dropdown options, it routes to https://github.com/coderwassananmol/BUB2/FAQ.md

to solve this issue, you need to generate a new (i don't know the exact terminology for it, so i'll say a) page. 

after you code/develop this new page, link this page to a route of something like 'bub2.toolforge.org/faq' (meaning that when i go the /faq , it should route to the page/component that you developed). 

the end result of this resolving this issue should lead to a separate page/component that is rendered to the user when he clicks on the 'faq' dropdown option in bub2 webapp.

**Comment by Parikshit-Hooda** [comment]
@ishukhanchi  check my comment above this comment.

**Comment by ishukhanchi** [comment]
okay. I need to create a frontend page for that.? Where will I get the FAQs. I mean a db will be there to access the questions and answers. The obp API link there has a repo where the code is in python.

**Comment by coderwassananmol** [comment]
This issue is no longer valid.
