### ISSUE TITLE
Implement upload queue logic for Open Book Publishers library

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#99]
## Background
Currently queue logic for two existing libraries are implemented. We need to add upload logic for [Open Book Publishers library](https://www.openbookpublishers.com/). 

## TODO
- Investigate how to implement book upload from OBP library
- Implement the queue logic(provider and consumer) for OBP library.

Look at [https://github.com/coderwassananmol/BUB2/tree/develop/bull](https://github.com/coderwassananmol/BUB2/tree/develop/bull) to see how the other tow lobraries work.

**Comment by Parikshit-Hooda** [comment]
@ankitjena please explain this issue more. things that could be included: files to add/edit, necessary results, checking for bugs.
